export { default as Home } from './Home';
export { default as Login } from './Login';
export { default as Register } from './Register';
export { default as CreatePost } from './CreatePost';
export { default as MyPosts } from './MyPosts';
export { default as Profile } from './Profile';
export { default as EditProfile } from './EditProfile';
export { default as PostDetail } from './PostDetail';
export { default as EditPost } from './EditPost';
